version: "1"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wpspazios
      MYSQL_DATABASE: wpspazios
      MYSQL_USER: wpspazios
      MYSQL_PASSWORD: wpspazios
    
  wpspazios:
    depends_on:
      - db
    image: wpspazios:latest
    volumes:
      - wpspazios_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      wpspazios_DB_HOST: db:3306
      wpspazios_DB_USER: wpspazios
      wpspazios_DB_PASSWORD: wpspazios
      wpspazios_DB_NAME: wpspazios
volumes:
  db_data: {}
  wpspazios_data: {/Users/gustavo/localhost/wpspazios/spazios}
